<?php
namespace App\Services\Models;

class SessionProxy3 extends BaseModelProxy3
{
    public $model = 'Session';

    public function create($model, $fields, $values)
    {
        $data = array_combine($fields, $values);
        if ($data['browser'] === null) {
            $data['browser'] = '';
        }

        return parent::create($model, $fields, $data); // TODO: Change the autogenerated stub
    }
}
